Разметка по БЭМ все красиво классно и вкусно почти)
htmlacademy-adaptive/1096051-mishka-23 pull request #2
Opened 2021-07-23 06:44 UTC by Problemon

2021-07-24 10:05 UTC, wrgraff requested changes
Хорошая работа, ты молодец.
Подокапывался до тебя побольше )

Вот еще небольшая поправка:
Шрифты надо в нижнем регистре все переименовать — 👎

2021-07-24 10:05 UTC, wrgraff commented on source/index.html
> +      <p class="modal-basket__text">Добавить в корзину</p>
Ты не переусложнил?
По-моему, "Добавить в корзину" как заголовок даже лучше подходит для этой модалки, чем твой придуманный.
Представь, что у нас еще параметр цвета добавится при выборе. Что тогда будет, последовательно всплывут модалки "Выбор размера товара" и "Выбор цвета товара", или одна модалка "Добавить в корзину", но с двумя параметрами?

Я понимаю, что "Добавить в корзину" не очень благозвучен в роли заголовка.
Но во-первых, это потому что UX-дизайнер осел, а во-вторых, этот текст все же помогает хорошо понять что именно в этой модалке.

2021-07-24 10:05 UTC, wrgraff commented on source/index.html
> +      <button class="modal-basket__button" type="submit"></button>
А в кнопке где текст? О_о

2021-07-24 10:05 UTC, wrgraff commented on source/index.html
> +    <div class="modal-basket__fade"></div>
Не надо нам лишних элементов, придумаем как быть с маской и без него.

2021-07-24 10:30 UTC, Problemon commented
Ок через 5 дней xD

2021-07-28 22:39 UTC, wrgraff requested changes
Шрифты не переименовались. Точнее, не зафиксировались.
Иногда изменение регистра не фиксируется. в таких случаях можно изменить имя совсем или удалить файл и вернуть. То есть, сделать явно заметное именение, закоммитить, а затем вернуть нужное имя и закоммитить как надо.

Это важный момент, придется разбираться!

2021-07-28 22:39 UTC, wrgraff commented on source/index.html
> +          <img class="navigation__logo logo" src="img/logo-mobile.svg" alt="">
Обычно все-таки блок лого объявляется на ссылке.
А смысл от него на одной картинке то?

2021-07-28 22:39 UTC, wrgraff commented on source/index.html
> +          <p class="popular-product__name title">Вязаные корзинки</p>
Нууу, сойдет )
Но это совсем разные элементы

2021-07-28 22:39 UTC, wrgraff commented on source/index.html
>          <button class="navigation__toggle"><span class="visually-hidden">Открыть меню</span></button>
Тут тоже вложенный тег в одну строку, кстати

2021-07-28 22:39 UTC, wrgraff commented on source/index.html
> +          <img class="copyright__icon" src="img/icon-htmlacademy.svg" alt="Логотип академии">
Ты понимаешь, что скринридер прочитает **все**?
Он скажет:
> Разработано в HTMLacademy перейти на страницу интенсива от HTMLacademy Логотип академии

Какая-то ересь выходит )

2021-07-28 23:23 UTC, wrgraff approved these changes

2021-07-28 23:23 UTC, wrgraff commented on source/index.html
> +          <img class="copyright__icon" src="img/icon-htmlacademy.svg" aria-hidden="true"  alt="">
2 пробела перед альтом

2021-07-28 23:23 UTC, wrgraff commented on source/index.html
> +          <h3 class="popular-product__name title">Вязаные корзинки</h3>
Внутри заголовка лучше.
А то получается странное. Озаглавили контент вторым уровнем, а все, что в нем есть — третьим.
Выглядит примерно как список из одного пункта с вложенным списком.

2021-07-28 23:23 UTC, merged