Module3 task1
htmlacademy-adaptive/1096051-mishka-23 pull request #4
Opened 2021-08-04 23:09 UTC by Problemon

2021-08-06 19:44 UTC, wrgraff requested changes
Подобную работу в следующий раз я отправлю на доработку без проверки.
Фразу "сделать больше, чем требуется" можно понимать по разному. Одно дело, если ты добавляешь больше деталей по теме. Другое — делаешь то, что делать не нужно.

Тем более, ты отклоняешься от плана, не обсудив это с наставником.
А я вынужден 2 с лишним часа разбирать задание теперь с тонной ошибок, которых можно было и не делать.

Ни сеток, ни декора в задании не было. Оно рассчитано на базовые стили, и именно поэтому в нем все 3 страницы в одном задании. Оно бы не стало слишком большим. А теперь — стало.

В результате твоего неуемного энтузиазма, направленного не в ту сторону:
- я не комментировал и никак не оценивал нюансы стилизации, хотя мог бы рассказать что-то о `transition` том же и тем, как стоит работать с ним. Потому что после разгребания кучи ошибок у меня нет времени и сил на это;
- ты наделал кучу ошибок, которые я не могу внятно прокомментировать, так как эта тема еще не пройдена. Это касается проблем с декоративными элементами и мелкими сетками;
- о дополнительных рекомендациях по темам, которые ты затронул раньше времени речи вообще не идет. Одна просочилась про доступность чекбоксов, но и только;
- куча времени потрачено впустую на то, чтобы сделать работу неправильно. Вместо этого ты мог сделать то, что нужно, и давно делать следующую часть.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +  border-image: url("../../img/zigzag.svg") 8 round;
Что такое "8"?

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +}
Очередные флексы без повода

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +  order: -1;
Порядок как относится к базовой стилизации?

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/production.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +  padding: 28.5px 10px 26.5px 76px;
Доли пикселей недопустимы

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/type-list.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/user-list.scss
> +  padding: 28.5px 10px 26.5px 76px;
Доли пикселей недопустимы

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/video.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/video.scss
> +  flex-direction: column;
Бесполезный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/global/fonts.scss
> +    url("../../fonts/opensans-regular.woff");
Путь неправильно указал

2021-08-06 19:44 UTC, wrgraff commented on source/sass/global/fonts.scss
> +    url("../../fonts/opensans-bold.woff2"),
Не указал формат шрифта

2021-08-06 19:44 UTC, wrgraff commented on source/sass/global/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
Нормазайз — бесполезный мусор на самом деле, 90% его кода бесполезна полностью

2021-08-06 19:44 UTC, wrgraff commented on source/sass/global/varriables.scss
> +$emerald-30: hsla(168, 54%, 60%, 0.3);
Кроме понтов эта цветовая схема полезна хоть чем-то?
Такие цветовые схемы надо использовать с кастомными свойствами и работать с ними правильно.
Здесь это абсолютно бесполезная запутанность, которая в кашу превратится когда придется больше цветов добавить

2021-08-06 19:44 UTC, wrgraff commented on source/sass/style.scss
> +@import "global/varriables.scss";
```suggestion
@import "global/variables.scss";
```

2021-08-06 19:44 UTC, wrgraff commented on source/sass/global/mixins.scss
> +  display: block;
Абсолютное позиционирование создает элемент блочным

2021-08-06 19:44 UTC, wrgraff commented on source/sass/global/mixins.scss
> +@mixin stick($top, $left: 0) {
На самом деле уже через неделю другой работы вернувшись к этому коду ты не вспомнишь что там за параметры надо передать.
И вообще, не сказал бы, что 2 использования кода — уже повод к созданию миксина.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +  height: 14px;
Решение плохое, а почему — ты видимо узнать не хочешь.
Это вопрос сеток и декоративных элементов, которые присылают в ПР гораздо меньшего объема.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +  }
Ты поставил класс скрытия по умолчанию, чем [нарушил ТЗ](https://up.htmlacademy.ru/adaptive/23/project/mishka#mishka-3-6)

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +  &--vissible {
```suggestion
  &--visible {
```

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +  flex-direction: column;
Необязательный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  max-width: 334px;
Размеры должны определяться сеткой, при больших размерах сетка должна перестраиваться.
Какие и где ограничения для нормальной работы резины нужно выставить определяется на уже готовых сетках

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  flex-direction: column;
Необязательный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  margin-bottom: 22.5px;
Пиксели допустимо использовать только в целых значениях.
Нельзя отобразить пол пикселя. Это создаст размытый элемент.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  justify-content: space-between;
Плохой метод, нужно предусматривать склеивание элементов даже там, где это кажется невозможным.
На данный момент флекс отсюда нужно удалить и сделать как положено в соответствующем разделе.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  border-image: url("../../img/zigzag.svg") 8 round;
Путь указан неверно.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +    background: url("../../img/icons/arrow.svg") no-repeat;
Ошибка в пути к картинке

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/textarea.scss
> +  flex-direction: column;
Бессмысленный флекс

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/textarea.scss
> +  height: 142px;
Сперва высоту поля ввода нужно задать отступами, размером шрифта и высотой строки.
И только затем если совсем не получается подстроиться везде — менять высоту

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/textarea.scss
> +  }
Решение с линией на данный момент нужно удалить.

2021-08-06 19:44 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +  justify-content: space-between;
Такое распределение элементов не позволит нормально работать переполнению.
Вообще, во всех ошибках по сеткам их нужно не исправить, а удалить.

2021-08-06 23:00 UTC, Problemon commented on source/sass/blocks/textarea.scss
> +  flex-direction: column;
А как мне его заголовок тогда выше него поставить?

2021-08-08 12:04 UTC, wrgraff requested changes
Ты что, пропустил плашку "Показать еще 100500 комментариев"?

2021-08-08 12:04 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +    background: url("../img/icons/arrow.svg") no-repeat;
Лучше вообще отдельно указывать свойства картинки и ввести это в привычку.
Это обезопасит от случайного перезаписывания всех свойств разом.

2021-08-08 12:04 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +    background: url("../../img/icons/check-mark.svg") 50% 50% no-repeat;
Исправил путь в одном месте и все?

2021-08-08 20:09 UTC, Problemon commented on source/sass/blocks/about.scss
> +  padding-right: 10px;
Это я текст пытался ровнять по ПП на 320 ;D

2021-08-08 20:23 UTC, Problemon commented on source/sass/blocks/modal-basket.scss
> +  transform: translate(-50%, -50%);
А я читал, что он наоборот менше жрет xD
![Screenshot_3](https://user-images.githubusercontent.com/49299300/128644657-98ef8f07-ecc0-4a57-900e-a883f9723ec9.jpg)

2021-08-08 20:42 UTC, Problemon commented on source/sass/global/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
Я на лайве просто увидел, и не посмотрел что он не нужен уже по критериям, ну пускай будет уже.

2021-08-08 20:49 UTC, Problemon commented on source/sass/global/varriables.scss
> +$emerald-30: hsla(168, 54%, 60%, 0.3);
Я долго думал над цветами, а как правильно их называть если они немного отличатся, я думал может препроцессорные функции юзать или миксин с атрибутом, я знал что названия не пойдут, но куда их девать.

2021-08-08 22:41 UTC, Problemon commented on source/sass/global/mixins.scss
> +@mixin stick($top, $left: 0) {
Я его просто заюзал чтобы понять как юзается)

2021-08-08 23:08 UTC, Problemon commented on source/sass/blocks/navigation.scss
> +  &--vissible {
sssssssssssssss

2021-08-08 23:19 UTC, Problemon commented on source/form.html
> +                <span class="input-contact__label input-contact__label--email">E-mail</span>
Про то что я написал "Введите ваш"? Я не совсем понял про что именно идет речь. У телефона тоже убрал.

2021-08-09 18:13 UTC, wrgraff commented on source/sass/blocks/about.scss
> +  padding-right: 10px;
ПП на базовой стилизации...

2021-08-09 18:17 UTC, wrgraff commented on source/sass/blocks/modal-basket.scss
> +  transform: translate(-50%, -50%);
Тут видимо расхождение.
При анимации, когда вызывается перерисовка, перемещение через `transform` будет более производительно, чем через параметры абсолютного позиционирования, например.
И тем более чем отступы — они будут еще больше перерисовок выделять.

Но когда речь про статичный элемент, самое лучшее — элементарный `margin`. Ну или можно использовать `calc` в параметрах позиционирования

2021-08-09 18:18 UTC, wrgraff commented on source/sass/global/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
Ну неплохо бы ощутить на себе каково писать без нормалайза.
_Спойлер: ты ничего не заметишь_

2021-08-09 18:21 UTC, wrgraff commented on source/sass/global/mixins.scss
> +@mixin stick($top, $left: 0) {
Ты вот умный и активный: попробуй написать и понять как работает самый удобный в мире миксин.
Вот такой (хе-хе):
```scss
@include breakpoint(large) {
  color: $black;
}
```

Ну или хотя бы так:

```scss
@include breakpoint($breakpoint-large) {
  color: $black;
}
```

2021-08-09 18:22 UTC, wrgraff commented on source/form.html
> +                <span class="input-contact__label input-contact__label--email">E-mail</span>
Да. Потому что это инпут. Понятно, что надо ввести. Понятно, что свои данные. Текст не особо добавляет пользы )

2021-08-09 18:46 UTC, wrgraff commented on source/sass/blocks/categories.scss
> +  background-color: darken($white, 2);
Цветовые функции, меняющие цвет, запрещены [критерием Д8](https://up.htmlacademy.ru/adaptive/23/criteries#d8).
Ты можешь использовать функции, которые форматируют цвет в другой формат (из hex в rgb, например) или добавляют alpha-канал. Но менять сам цвет нельзя

2021-08-09 18:46 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> -  }
Я ж написал "надо бы заставить", а не "удали".
Я уже посмотрел этот код. Он вернется и придется его опять проверять =(

2021-08-09 18:46 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> -
Опять же. Разделяй комментарии, где требуется что-то сделать, и те, где я просто поругался, чтобы ты учел на будущее чего лучше не делать.
Удалять то, что уже написано просто потому, что это было рано писать — такое же поспешное действие, как и написать лишнего.
Удалить нужно было только то, что написано заранее и при этом написано неправильно.

2021-08-09 18:46 UTC, wrgraff commented on source/sass/blocks/modal-basket.scss
> +  left: 0;
Ну тогда и `top` и `bottom` должны быть наверное 0

2021-08-09 18:46 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +  color: lighten($black, 27);
Снова цветовая функция. И вижу еще несколько таких.
Придется убирать, посмотри их по документу: не буду каждую комментировать

2021-08-09 18:46 UTC, wrgraff commented on source/sass/global/varriables.scss
> +$emerald-30: hsla(168, 54%, 60%, 0.3);
Ты просто велосипед изобретаешь 🤷

2021-08-09 18:49 UTC, wrgraff requested changes
С цветами изобретаешь велосипед )
Есть уже давно опробованная система именования, которую я давал в пример.
Она удобна тем, что более-менее универсальна. Другие системы тоже есть и даже могут быть удобны, но нужно чтобы на них опирался дизайн, иначе получается натягивание совы на глобус.

2021-08-09 20:45 UTC, Problemon commented on source/sass/blocks/categories.scss
> +  background-color: darken($white, 2);
Самое интересное, что я помнил что вроде есть такой критерий, решил проверить и не увидел его xD

2021-08-09 21:09 UTC, wrgraff commented on source/sass/blocks/categories.scss
> +  background-color: darken($white, 2);
Надо было внимательно смотреть!
Там же не так много в разделе про препроцессор критериев

2021-08-09 23:48 UTC, Problemon commented on source/sass/blocks/modal-basket.scss
> +  left: 0;
Так я чет не понимаю, я хочу сделать так чтобы он бы отцентрован и работало переполнение, чтобы высота увеличивалась при переполнении, но если я задам по нулям то он растянется, или прийдется указывать максимальную высоту.

2021-08-09 23:50 UTC, Problemon commented on source/sass/blocks/modal-basket.scss
> +  left: 0;
Вот поэтому я и использовал тот метод 
![Screenshot_5](https://user-images.githubusercontent.com/49299300/128788289-0d72daf7-80c9-4f04-b977-17a9769c35c8.jpg)

2021-08-09 23:58 UTC, Problemon commented
попытка номер двестимиллионовпятсотпятдесятвосесьодинадцатогочетырепятьшестьпятого

2021-08-10 18:15 UTC, wrgraff approved these changes

2021-08-10 18:15 UTC, wrgraff commented on source/sass/global/variables.scss
> +$color-black-270:hsl(0, 0%, 27%);
Обычно черный и белый без градаций, а с градациями серый

2021-08-10 18:15 UTC, merged