Хз жесть какая-то с этими переворотами перемещениями
htmlacademy-adaptive/1096051-mishka-23 pull request #5
Opened 2021-08-11 02:27 UTC by Problemon

2021-08-12 00:22 UTC, wrgraff requested changes

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  }
На данный момент твои стрелки перекрыли текст:
![изображение](https://user-images.githubusercontent.com/37917037/129118749-9bad54c4-d624-4841-bf09-57efc33e05f7.png)
Из-за этого текст там под плашкой и его невозможно выделить

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +    display: grid;
Лучше сразу же задавать `gap`, чтобы ни при каких условиях текстовый блок (как бы она пока ни был мал) не мог слипнуться с другим блоком:
![изображение](https://user-images.githubusercontent.com/37917037/129118882-4492f280-1074-4ff4-91a0-f672dea0299e.png)

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  }
Придумал хитро, но не мешало бы предусмотреть, что в элементе с именем автора стоит предусмотреть справа безопасное место, так как над ним всегда будут кнопки, и текст туда попасть не должен.
![изображение](https://user-images.githubusercontent.com/37917037/129119027-aabbe5fc-d012-4e95-8421-ae7bcb6e0fd5.png)

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/site-list.scss
>    cursor: pointer;
У ссылок и так поинтер, зачем он тут сдался?

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/user-list.scss
>    cursor: pointer;
И тут непонятно зачем поинтер.
Ссылка без поинтера может быть только по причине отсутствия `href`. А раз его нет, она не кликабельна. А раз не кликабельна, то и поинтер ей не нужен.
А ты попортил эту логику.

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +    grid-auto-rows: auto;
А это зачем? Ничего не дает, потому что это значение по умолчанию

2021-08-12 00:22 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +    0 1px 0 $color-gray-930;
Вот эти тени твои там по макету пляшут уже где надо и где не надо.

https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/7abf096b248ebd2627dc7e46e4b7e22aa3d1b5af/source/sass/blocks/page-header.scss#L4-L6
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/7abf096b248ebd2627dc7e46e4b7e22aa3d1b5af/source/sass/blocks/site-list.scss#L21-L23
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/7abf096b248ebd2627dc7e46e4b7e22aa3d1b5af/source/sass/blocks/user-list.scss#L21-L23

Я сделал их поярче и [записал положение при разном размере экрана.](https://t.me/c/1594158829/2) Обрати внимание на то, что они часто появляются вообще не там, где нужно, а где нужно появляются вообще не всегда.

2021-08-12 21:04 UTC, Problemon commented on source/index.html
> +        <a class="navigation__delivery" href="#">Бесплатная доставка по России</a>
Ааа, это типо как преимущество?

2021-08-12 21:38 UTC, wrgraff commented on source/index.html
> +        <a class="navigation__delivery" href="#">Бесплатная доставка по России</a>
Вроде того. В интернет-магазинах часто делают такие пометки про доставку.

2021-08-12 23:54 UTC, Problemon commented on source/sass/blocks/navigation.scss
> +}
Серый фон можно наложенностью сделать на нижний блок

2021-08-12 23:58 UTC, Problemon commented on source/sass/blocks/container.scss
> +}
А про это я чет забыл)

2021-08-13 00:21 UTC, Problemon commented on source/sass/blocks/site-list.scss
>    cursor: pointer;
Смотрел раньше канал с 0 до 1: он там все делал - на всякий случай xD

2021-08-15 00:23 UTC, wrgraff commented on source/sass/blocks/navigation.scss
>    }
Да

2021-08-15 00:38 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +    left: 0;
Обнуляешь?
Если имеется ввиду возврат к значению по умолчанию, то по умолчанию у них значение не "0"

2021-08-15 00:55 UTC, wrgraff commented on source/sass/blocks/container.scss
> +  }
А ты думаешь, если добавить максимальную ширину сразу, без медиа-запроса, она вдруг сработает на мобильной версии? )

2021-08-15 00:55 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  }
Я в FF работаю

2021-08-15 01:00 UTC, wrgraff commented on source/sass/blocks/site-list.scss
>    cursor: pointer;
Это для тех, кто не понимает как работает веб?

2021-08-15 01:02 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +    0 1px 0 $color-gray-930;
А зачем они вообще нужны?
Кроме того, что мешают, они ничего не делают.
Работать это не будет.

2021-08-15 01:09 UTC, wrgraff requested changes

2021-08-15 01:09 UTC, wrgraff commented on source/sass/blocks/user-list.scss
> +    box-shadow: none;
Обнуление тени, которая не нужна, потому что тенью на элементах там рамки не сделать.
Тени убрать придется. А обнуление наверняка забудется. И будет болтаться бесполезное правило.

Лишняя причина не делать преждевременной оптимизации и не забегать вперед.

2021-08-15 21:45 UTC, Problemon commented on source/sass/blocks/container.scss
> +  }
десктоп головного мозга просто

2021-08-15 21:49 UTC, Problemon commented on source/sass/blocks/reviews.scss
> +  }
Легкие пути? Мы такие не слышали

2021-08-16 21:26 UTC, wrgraff approved these changes

2021-08-16 21:26 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +      "sale  .     del";
`del`? А что там было про удаление...

2021-08-16 21:26 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +      "sale  .     del";
Можно использовать свободное место под меню, чтобы оно переполнялось сложнее
```suggestion
      "sale sale del";
```

2021-08-16 21:26 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +    grid-area: del;
Так это доставка!
И как я мог узнать такое по сокращению?

2021-08-16 21:26 UTC, merged

2021-08-16 22:12 UTC, Problemon commented on source/sass/blocks/navigation.scss
> +    grid-area: del;
xD Удаление