Адаптив большой блок внутри страница
htmlacademy-adaptive/1096051-mishka-23 pull request #6
Opened 2021-08-17 23:13 UTC by Problemon

2021-08-18 08:47 UTC, wrgraff requested changes
Ну в целом все красиво, но непонятно что со страницей формы стряслось =)

2021-08-18 08:47 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    padding: 0;
А почему ты только с планшета сбрасываешь отступ?
На мобильной версии он ведь тоже есть =)

2021-08-18 08:47 UTC, wrgraff commented on source/sass/blocks/product.scss
> +
Кажется, твоя реализация рамки пока не очень работает.
Имей ввиду:
![изображение](https://user-images.githubusercontent.com/37917037/129864444-87b611f1-62e0-4ec7-8478-0505016ebb8d.png)

2021-08-18 08:47 UTC, wrgraff commented on source/catalog.html
> +          <ul class="navigation__sale-menu">
А чего это в навигации нет ссылок на форму?

https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/c9bc4befaa769abcc267cb870814173c5e9df87c/source/catalog.html#L33-L35

2021-08-18 08:47 UTC, wrgraff commented on source/sass/blocks/form.scss
А где сетки то на странице формы? ))

![изображение](https://user-images.githubusercontent.com/37917037/129865009-e9d5c805-f887-45b0-a016-166e8e5d899d.png)

2021-08-18 08:47 UTC, wrgraff commented on source/sass/blocks/field-group.scss
> +  }
Вряд ли ты сможешь сделать таким образом сетку )
Эти блоки же сами должны рядом стоять, а не контент внутри них

2021-08-18 08:47 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    width: 315px;
Ширину лучше не определять руками, а сделать так, чтобы ширина была определена выше: там, где карточки формируются в колонки. А картинка пускай лучше просто занимает всю карточку

2021-08-18 08:47 UTC, wrgraff commented on source/sass/blocks/video.scss
> +      "player  info";
Понравилось что ли? =)
Смотри, иногда указание по линиям все-таки уместнее бывает.

2021-08-18 20:33 UTC, Problemon commented on source/sass/blocks/video.scss
> +      "player  info";
Ну да, я так думаю что по линиям лучше всего, если при разном количестве контента нужно чтобы какой-либо элемент занимал все до конца строки или столбца или так далее.

2021-08-18 20:34 UTC, Problemon commented on source/sass/blocks/video.scss
> +      "player  info";
`grid-column: 1/-1` типо такого, ну или спаны

2021-08-18 20:45 UTC, wrgraff commented on source/sass/blocks/video.scss
> +      "player  info";
Да, это очень хороший пример

2021-08-18 21:03 UTC, Problemon commented on source/sass/blocks/product.scss
> +    padding: 0;
Потому что контейнер

2021-08-18 21:10 UTC, Problemon commented on source/sass/blocks/form.scss
Как это?
У меня есть сетки

2021-08-18 21:14 UTC, Problemon commented on source/sass/blocks/field-group.scss
> +  }
Так это для легенды

2021-08-18 21:18 UTC, Problemon commented on source/sass/blocks/field-group.scss
> +  }
Какие блоки рядом, я просто не понял)?

2021-08-18 21:22 UTC, Problemon commented on source/sass/blocks/product.scss
> +    padding: 0;
Тут просто такая ситуация, что на контейнер не повесить этих отступов для мобилок, так как некоторые блоки идут до краев экрана и из-за этого я отдельно на каждый секционный блок на который нужно, вешал отступы.

2021-08-18 21:24 UTC, Problemon commented on source/sass/blocks/product.scss
> +    padding: 0;
![Screenshot_1](https://user-images.githubusercontent.com/49299300/129974232-f8593cb5-a60f-432d-b62e-8ecbc244ba00.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/49299300/129974234-f4645335-1cff-4ae4-abc9-9f270d4d90ea.jpg)
Вот допустим один из примеров

2021-08-19 09:08 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    padding: 0;
В таком случае возможно для какого-то элемента не стоит применять общий `container`. Или применить и переназначить стили (более хрупкий вариант, требуется чтобы стили контейнера шли раньше переопределения)

2021-08-19 09:11 UTC, wrgraff commented on source/sass/blocks/field-group.scss
> +  }
Это к проблеме легенды относилось )

2021-08-19 09:11 UTC, wrgraff commented on source/sass/blocks/form.scss
Пока сойдет

2021-08-19 09:12 UTC, Problemon commented on source/sass/blocks/product.scss
> +    padding: 0;
`full-container`? xD Я не знаю как его можно назвать, ну или с какой-нибудь привязкой к мобильному названию, потому что на остальных размерах они себя как остальные элементы ведут

2021-08-19 09:18 UTC, wrgraff approved these changes

2021-08-19 09:18 UTC, wrgraff commented on source/sass/blocks/field-group.scss
> +  }
На самом деле, легенда все еще идет перед сеткой. Это создает некоторые проблемы.

2021-08-19 09:18 UTC, merged