Adaptive microgrid
htmlacademy-adaptive/1096051-mishka-23 pull request #7
Opened 2021-08-21 22:53 UTC by Problemon

2021-08-22 19:46 UTC, wrgraff requested changes

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/field-group.scss
> +  float: left;
Единственный нюанс, могут докопаться на защите. Якобы, сетка сделана на флоатах.
На самом деле, это будет чистой воды докапывание, потому что это фикс/лайфхак, а сетка у тебя гридами сделана. Так что может статься, что придется повоевать с проверяющим

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/logo.scss
> +.logo-foote__icon {
Это вообще что? =)
Класс странный сам по себе, откусанный какой-то.
Ну и вообще, это файл блока `logo`, тут не может быть `logo-foote` или `logo-footer` или `logo-barmaglot`

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +    grid-template-columns: 3.5fr 4fr;
Обычно в таких случаях все-таки иначе решают проблему =)
Тут и сложно, и непонятно как оно считаться будет при ровном фиксированном гэпе... Предположить какой размер будет довольно сложно (или ты гений математики?)

Вообще, все проще.
У нас ровно пополам делится, но отступ за счет левой части.
Элементарно, Ватсон: правая половина — 50%, гэп — фиксированный, левый — все оставшееся. Прикинь, можно так и написать 😀

```suggestion
    grid-template-columns: 1fr 50%;
```

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +    grid-template-columns: 133px 2.7fr 5fr;
Подумай, как и здесь можно решить проблему без странных значений вроде `2.7`

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +    word-break: break-word;
А это зачем вообще?

2021-08-22 19:46 UTC, wrgraff commented on source/index.html
> +        <a class="contacts__button button button--review" href="#">Напишите нам</a>
А почему в контактах кнопка `button--review`? Я в стилях увидел, обыскался ее в блоке отзывов

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/site-list.scss
>      display: flex;
А переполнение как же?

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/site-list.scss
>    background-color: $color-white;
Фон скорее мешает:
![изображение](https://user-images.githubusercontent.com/37917037/130367992-2a3e3050-76d5-420b-a3d5-d7a4646aa66c.png)

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +  grid-template-columns: repeat(3, 1fr);
А если еще одна иконка добавится? Переверстывать?

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +    width: 140px;
Тут сразу переполнение поломал

2021-08-22 19:46 UTC, wrgraff commented on source/sass/blocks/user-list.scss
> +    justify-content: space-between;
На что это влияет? Там же элементы вплотную стоят

2021-08-22 20:13 UTC, Problemon commented on source/index.html
> +          <span class="navigation__button-stick"></span>
Ну блин, тогда анимация не получится)

2021-08-22 20:16 UTC, Problemon commented on source/js/menu.js
> +      swapClass(menuButtonStick, "navigation__button-stick--opened", "navigation__button-stick--closed");
Закопипастил просто)

2021-08-22 20:18 UTC, Problemon commented on source/sass/blocks/navigation.scss
> +    transition: transform 0.4s ease;
Баг xD

2021-08-22 20:56 UTC, Problemon commented on source/sass/blocks/user-list.scss
> +}
Это ненужная деталька

2021-08-22 20:59 UTC, Problemon commented on source/sass/blocks/page-header.scss
> +  background-image: linear-gradient(to bottom, $color-white calc(100% - 44px), $color-gray-980 calc(100% - 44px));
Градиент, сам увидел уже с утра xD

2021-08-22 21:54 UTC, Problemon commented on source/sass/blocks/button.scss
> +  }
Я так изначально думал сделать, но подумал что будет неправильно)

2021-08-22 21:58 UTC, Problemon commented on source/sass/blocks/field-group.scss
> +  float: left;
Докажу ему, пускай предложит иной вариант если такой имеется.

2021-08-22 21:58 UTC, Problemon commented on source/sass/blocks/logo.scss
> +.logo-foote__icon {
xD а-ахахзпзхазхапзха

2021-08-22 21:59 UTC, Problemon commented on source/sass/blocks/logo.scss
> +.logo-foote__icon {
У меня мозг уде просто поплыл тогда

2021-08-22 22:01 UTC, Problemon commented on source/sass/blocks/popular-product.scss
> +    grid-template-columns: 3.5fr 4fr;
А что такое проценты xD Фракции темы, ты думаешь я сидел в голове просчитывал, подбирал пропорции, просто так чтоли?

2021-08-22 22:08 UTC, Problemon commented on source/sass/blocks/popular-product.scss
> +    word-break: break-word;
В случае, если текст захотят изменить чтобы он проходил на переполнение

2021-08-22 22:10 UTC, Problemon commented on source/index.html
> +        <a class="contacts__button button button--review" href="#">Напишите нам</a>
it's a trap

2021-08-22 22:36 UTC, Problemon commented on source/sass/blocks/site-list.scss
>    background-color: $color-white;
Заметил уже)

2021-08-22 22:38 UTC, Problemon commented on source/sass/blocks/social-list.scss
> +  grid-template-columns: repeat(3, 1fr);
Ну так она снизу встанет)

2021-08-23 21:00 UTC, wrgraff commented on source/index.html
> +          <span class="navigation__button-stick"></span>
Давай сперва защита, потом свистелки и перделки приделаешь =)

2021-08-23 21:01 UTC, wrgraff commented on source/js/menu.js
> +      swapClass(menuButtonStick, "navigation__button-stick--opened", "navigation__button-stick--closed");
Закопипастил — поправь =)

2021-08-23 21:05 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  }
Будет правильно

2021-08-23 21:06 UTC, wrgraff commented on source/sass/blocks/field-group.scss
> +  float: left;
В любом случае, этим правилом не строится сетка =)
Им только фиксится браузерный кринж

2021-08-23 21:07 UTC, wrgraff commented on source/sass/blocks/popular-product.scss
> +    grid-template-columns: 3.5fr 4fr;
Верстальщики не любят считать =/

2021-08-23 21:07 UTC, Problemon commented on source/index.html
> +          <span class="navigation__button-stick"></span>
xD

2021-08-23 21:11 UTC, Problemon commented on source/sass/blocks/popular-product.scss
> +    grid-template-columns: 3.5fr 4fr;
А как же синусы и косинусы для анимации круга
Я такое видел xD

2021-08-23 21:15 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +  grid-template-columns: repeat(3, 1fr);
Но в ширину есть место. Пока есть, надо использовать

2021-08-23 21:18 UTC, Problemon commented on source/sass/blocks/social-list.scss
> +  grid-template-columns: repeat(3, 1fr);
Чет я мучался с гридом и подходящего варианта не нашел под твои запросы
и grid-auto-flow пробовал и auto-fill

2021-08-23 21:23 UTC, wrgraff approved these changes

2021-08-23 21:23 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +  &:last-child() {
Без скобок пишутся первый и последний

2021-08-23 21:23 UTC, wrgraff commented on source/sass/blocks/about.scss
> +  background-repeat: no-repeat;
Повторение одного и того же свойства
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/00bece53a43cc6a592b3b7446fdf983a76d245c2/source/sass/blocks/about.scss#L61
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/00bece53a43cc6a592b3b7446fdf983a76d245c2/source/sass/blocks/about.scss#L67
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/00bece53a43cc6a592b3b7446fdf983a76d245c2/source/sass/blocks/about.scss#L73
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/00bece53a43cc6a592b3b7446fdf983a76d245c2/source/sass/blocks/about.scss#L78
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/00bece53a43cc6a592b3b7446fdf983a76d245c2/source/sass/blocks/about.scss#L83
https://github.com/htmlacademy-adaptive/1096051-mishka-23/blob/00bece53a43cc6a592b3b7446fdf983a76d245c2/source/sass/blocks/about.scss#L89

2021-08-23 21:23 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +      $color-gray-980 calc(100% - 43px));
А ты не думал, что вместо `100% - XXpx` проще тупо написать `to top`?

2021-08-23 21:23 UTC, merged

2021-08-23 21:24 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +  grid-template-columns: repeat(3, 1fr);
Ну потому что это флексом делается 😀😀😀

2021-08-23 21:30 UTC, Problemon commented on source/sass/blocks/page-header.scss
> +      $color-gray-980 calc(100% - 43px));
xD