Декоративные элементы внутренних страниц
htmlacademy-adaptive/1096051-mishka-23 pull request #8
Opened 2021-08-26 08:40 UTC by Problemon

---
:mortar_board: [Декоративные элементы внутренних страниц](https://up.htmlacademy.ru/adaptive/23/user/1096051/tasks/10)

:boom: https://htmlacademy-adaptive.github.io/1096051-mishka-23/8/

2021-08-27 23:29 UTC, wrgraff requested changes

2021-08-27 23:29 UTC, wrgraff commented on source/catalog.html
> +                <span class="user-list__search-text">Поиск по сайту</span>
А что не так с классом `visually-hidden`?

2021-08-27 23:29 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    }
Все равно не то.
Тень должна появляться при наведении на саму карточку. Но тень — только под плашкой.

2021-08-27 23:29 UTC, wrgraff commented on source/sass/blocks/video.scss
> +    }
С видео логика такая же. Наводишь на карточку, тень появляется под плашкой.

2021-08-27 23:29 UTC, wrgraff commented on source/catalog.html
> +                <span class="visually-hidden">Добавить в корзину</span>
Можно бы еще на картинку добавить `aria-hidden="true"`, так как не надо ей в доступность лезть

2021-08-27 23:29 UTC, wrgraff commented on source/form.html
> +              <span class="field-group__heading-line"></span>
О нет, можно же это сделать без лишних пустых элементов.
Линия псевдоэлемент, а текст просто текст.

И твой любимый критерий про лишние элементы опять не проходит

2021-08-28 00:44 UTC, Problemon commented on source/sass/blocks/product.scss
> +    }
ПРоще на боди повешать проверку уже

2021-08-28 00:45 UTC, Problemon commented on source/form.html
> +              <span class="field-group__heading-line"></span>
ааааа точична

2021-08-28 00:45 UTC, Problemon commented on source/form.html
> +              <span class="field-group__heading-line"></span>
Я никогда просто псевдоэлемент без position absolute не использовал xD

2021-08-28 01:14 UTC, Problemon commented on source/catalog.html
> +                <span class="user-list__search-text">Поиск по сайту</span>
Создавать модификатор на котором перебивать потом свойства на дефолт до планшетной версии?

2021-08-28 01:15 UTC, Problemon commented on source/catalog.html
> +                <span class="user-list__search-text">Поиск по сайту</span>
Мне просто показалось так проще, потому что в любом случае придется код повторять, только в случае с модификатором его будет чуть побольше.

2021-08-28 01:15 UTC, Problemon commented on source/catalog.html
> +                <span class="user-list__search-text">Поиск по сайту</span>
Хотя если следовать БЭМ - то лучше сделать с модификатором

2021-08-29 16:10 UTC, wrgraff approved these changes

2021-08-29 16:10 UTC, merged